/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package Configure;

//import App_Data.Utility;
import java.awt.Frame;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.InputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;

/**
 *
 * @author IETECH
 */
public class ChooseFile extends javax.swing.JDialog {

    /**
     * Creates new form ChooseFile
     */
    
    int returnVal;
    InputStream in;
    public String Licence_str;
    public String Filepathname;
//    Frame Parent_frame;
    public ChooseFile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
//        Parent_frame = parent;
        initComponents();
        returnVal = Licence_FileChooser.showOpenDialog(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Licence_FileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Licence_FileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Licence_FileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Licence_FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Licence_FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Licence_FileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Licence_FileChooserActionPerformed
        // TODO add your handling code here:
        
//    if (evt.getSource() == Licence_FileChooser.openButton) {
//        System.out.println("YEA : " + evt.getSource());

        if (evt.getActionCommand() == JFileChooser.APPROVE_SELECTION) 
        {
            File file = Licence_FileChooser.getSelectedFile();
            //This is where a real application would open the file.
//            System.out.println("Opening: " + file.getName() );
//            System.out.println("Absolute path: " + file.getAbsolutePath() );

            Filepathname = file.getAbsolutePath();
            
            if (file.getAbsolutePath().length() > 0)
            {
                Path path = Paths.get(Filepathname);

                BufferedReader br = null;
                FileReader fr = null;
            
		try 
                {

                    fr = new FileReader(path.toString());
                    br = new BufferedReader(fr);

                    String sCurrentLine;

                    //br = new BufferedReader(new FileReader(FILENAME));
//                    Utility app_util = new Utility();

                    Licence_str = "";
//                    while ((sCurrentLine = br.readLine()) != null) 
                    if ((sCurrentLine = br.readLine()) != null) 
                    {
//                        System.out.println("READ LINE : " + sCurrentLine  +  "  DECRYPTED : " + app_util.decrypt_str(sCurrentLine.getBytes(), "YoUrAcct #withUs"));
                        System.out.println("READ LINE : " + sCurrentLine  );
//                        System.out.println("READ LINE : " + sCurrentLine  +  "  DECRYPTED : " + app_util.decrypt_str(sCurrentLine.getBytes(), "YoUrAcct #withUs"));
                         Licence_str = sCurrentLine;
                   }
                    
                    this.dispose();
//                    Parent_frame.dispose();
		} 
                catch (Exception e) {

                    e.printStackTrace();

		}            


//                return;                
            }

        } 
        else 
        {
            System.out.println("Open command cancelled by user." );
            System.exit(0);
        }
//   }         
    }//GEN-LAST:event_Licence_FileChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChooseFile dialog = new ChooseFile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser Licence_FileChooser;
    // End of variables declaration//GEN-END:variables
}
