/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mapping;

import MainApp.Utility;
import dbconnect.DB_OPS;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sogobanjo
 */
public class SubjectToTeacher extends javax.swing.JDialog {

    /**
     * Creates new form SubjectToTeacher
     */
    public SubjectToTeacher(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        DB_OPS ops = new DB_OPS();
        ops.createConnection();
        
         // ACADEMIC SESSION DROP DOWN
        String stmt ="select name from academic_session";
        ResultSet Rset = ops.sel_data(stmt);
        comboAcademicSession.removeAllItems();
        fill_list(comboAcademicSession,Rset);

        
        // SUBJECT DROP DOWN
         stmt ="select name from subject";
         Rset = ops.sel_data(stmt);
        comboSubjectTeacher.removeAllItems();
        comboSubjectTeacher.addItem("Select");
        fill_list(comboSubjectTeacher,Rset);
           
                
//        // POPULATING THE LIST BOX FOR TEACHERS
//        stmt ="select concat(staff_id,' ', first_name,' ',  middle_name, ' ', last_name) AS TeacherName " +
//                " from register_teacher  " +
//                " where id not in (select teacher_id from subject_to_teacher where academic_session_id = (select id from academic_session where name = '" + comboAcademicSession.getSelectedItem() + "') " +
//                " and subject_id = (select id from subject where name = '" + comboSubjectTeacher.getSelectedItem() + "'))) ";

        //ResultSet Rset = ops.sel_data(stmt);
        
//        System.out.println(stmt);
//        Utility myutil = new Utility();
//        myutil.fill_list(listTeachers, stmt);
        
        
         ops.close_conn();
         
         
         
        
             
    }

    
    
     private void fill_list(javax.swing.JComboBox JBox, ResultSet Rset)
    {
        try
        {
            
            while (Rset.next())
           {
               JBox.addItem(Rset.getString(1));
           }

        }
        catch(Exception ex)
        {
            
        }
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboSubjectTeacher = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTeachers = new javax.swing.JList<>();
        buttonMap = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboAcademicSession = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Map Subject to Teacher");

        jLabel2.setText("Subject");

        comboSubjectTeacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSubjectTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSubjectTeacherActionPerformed(evt);
            }
        });

        jLabel3.setText("Teacher");

        listTeachers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listTeachers.setEnabled(false);
        jScrollPane1.setViewportView(listTeachers);

        buttonMap.setText("Map");
        buttonMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMapActionPerformed(evt);
            }
        });

        jLabel4.setText("Session");

        comboAcademicSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMap)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSubjectTeacher, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboAcademicSession, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 154, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAcademicSession, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSubjectTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(buttonMap)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSubjectTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSubjectTeacherActionPerformed
        // TODO add your handling code here:
    
        
        String selObj = new String("" + comboSubjectTeacher.getSelectedItem());
//            System.out.println(selObj);
       
            if (selObj.trim().length() == 0)
                return;
            
        if (selObj.equalsIgnoreCase("Select"))
        {
//            System.out.println(comboSubjectTeacher.getSelectedItem());
        }
        else            
        {
//            System.out.println(comboSubjectTeacher.getSelectedItem());
                     // POPULATING THE LIST BOX FOR TEACHERS
//             String stmt ="select concat(staff_id,' ', first_name,' ',  middle_name, ' ', last_name) AS TeacherName " +
//                     " from register_teacher  " +
//                     " where id not in (select teacher_id from subject_to_teacher where academic_session_id = (select id from academic_session where name = '" + comboAcademicSession.getSelectedItem() + "') " +
//                     " and subject_id = (select id from subject where name = '" + selObj + "')) ";
//     //        ResultSet Rset = ops.sel_data(stmt);
//             System.out.println(stmt);
//
//             Utility myutil = new Utility();
//             myutil.fill_list(listTeachers, stmt);
//             listTeachers.setEnabled(true);
                refreshTeachersList();
        }

    }//GEN-LAST:event_comboSubjectTeacherActionPerformed

    private void refreshTeachersList()
    {
             String stmt ="select concat(staff_id,' ', first_name,' ',  middle_name, ' ', last_name) AS TeacherName " +
                     " from register_teacher  " +
                     " where id not in (select teacher_id from subject_to_teacher where academic_session_id = (select id from academic_session where name = '" + comboAcademicSession.getSelectedItem() + "') " +
                     " and subject_id = (select id from subject where name = '" + comboSubjectTeacher.getSelectedItem() + "')) ";
     //        ResultSet Rset = ops.sel_data(stmt);
             System.out.println(stmt);

             Utility myutil = new Utility();
             myutil.fill_list(listTeachers, stmt);
             listTeachers.setEnabled(true);
        
    }
    private void buttonMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMapActionPerformed
        // TODO add your handling code here:
        
        int sel_indices[];
        sel_indices = listTeachers.getSelectedIndices();
        
        
        
        if ( sel_indices.length == 0)
        {

//            app_util.MsgBox("Please Select at least a Table", "Configuration",this);
            JOptionPane.showMessageDialog(this, "Please Select at least a Teacher");
        }
        else
        {
            DB_OPS dbops = new DB_OPS();
        dbops.createConnection();

            DefaultListModel listModel = new DefaultListModel();
            
         String stmt = "insert into subject_to_teacher (academic_session_id, subject_id, teacher_id) " +
                " values ";
            for ( int i = 0; i < sel_indices.length; i++)
            {
                
                listModel.addElement(listTeachers.getModel().getElementAt(sel_indices[i]));
//         String stmt = "insert into subject_to_class (academic_session_id, subject_id, class_id) " +
//                " values (" +
              stmt +=  "((select id from academic_session where name = '" + comboAcademicSession.getSelectedItem() + "')," +
                "(select id from subject where name = '" + comboSubjectTeacher.getSelectedItem() + "')," +
                "(select id from register_teacher where staff_id = '" + listTeachers.getModel().getElementAt(sel_indices[i]).split(" ")[0] + "')" +
                 ")";

              
              //Remove comma from the last select statement
              if (i != sel_indices.length -1)
              {
                  stmt += ",";
              }
                  
            }
           
            
            System.out.println(stmt);   // Print the SQL statement for debugging purpose
            dbops.in_data(stmt);      
            if(dbops.error_msg.trim().length()==0)
            {
                JOptionPane.showMessageDialog(this,  " Successfuly Mapped");
                refreshTeachersList();

            }
            else
            {
                if (dbops.error_msg.trim().contains("PRIMARY"))
                JOptionPane.showMessageDialog(this, "Duplicate Entry Not Allowed "  + dbops.error_msg);
                else
                 JOptionPane.showMessageDialog(this, "Error Occured While Inserting "  + dbops.error_msg);
            }
           
              dbops.close_conn();
         }

        
        
        
        
    }//GEN-LAST:event_buttonMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectToTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectToTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectToTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectToTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SubjectToTeacher dialog = new SubjectToTeacher(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMap;
    private javax.swing.JComboBox<String> comboAcademicSession;
    private javax.swing.JComboBox<String> comboSubjectTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listTeachers;
    // End of variables declaration//GEN-END:variables
}
