/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainApp;


import Options.OptionsDialog;
import global.GlobalVar;
import Registration.RegistrationDialog;
import Registration.ActivateDeactivateTeacher;
import Mapping.SubjectToClass;
import Mapping.SubjectToTeacher;
import Mapping.TeacherToClass;
import Registration.RegisterTeachers;
import Registration.TimeTablePeriod;
import Student_affairs.SchoolAttendance;
import Student_affairs.SubjectAttendance;
import Student_affairs.CA_Exam;
import Student_affairs.CA_Exam_Setup;
/**
 *
 * @author sogobanjo
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        registrationMenu = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemRegStudents = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemRegTeachers = new javax.swing.JMenuItem();
        MenuItemActivate = new javax.swing.JMenuItem();
        MenuItemDeactivate = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuItemCreate = new javax.swing.JMenuItem();
        MenuItemGenerate = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        createOptions = new javax.swing.JMenu();
        bloodGroup = new javax.swing.JMenuItem();
        genotype = new javax.swing.JMenuItem();
        religion = new javax.swing.JMenuItem();
        sex = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        colour_of_the_eyes = new javax.swing.JMenuItem();
        state = new javax.swing.JMenuItem();
        local_govt = new javax.swing.JMenuItem();
        country = new javax.swing.JMenuItem();
        class_name = new javax.swing.JMenuItem();
        subject = new javax.swing.JMenuItem();
        menuItemAcademicSession = new javax.swing.JMenuItem();
        menuItemMaritalStatus = new javax.swing.JMenuItem();
        menuItemAcademicTerm = new javax.swing.JMenuItem();
        menuItemTimeTablePeriod = new javax.swing.JMenuItem();
        menuItemDayOfTheWeek = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItemSchoolAttended = new javax.swing.JMenuItem();
        jMenuItemTeachersPosition = new javax.swing.JMenuItem();
        jMenuItemSpecialAilment = new javax.swing.JMenuItem();
        jMenuItemFeeType = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuItemSubjectToClass = new javax.swing.JMenuItem();
        menuItemSubjectToTeacher = new javax.swing.JMenuItem();
        menuItemTeacherToClass = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrationMenu.setText("Registration");

        jMenu4.setText("Students");

        jMenuItemRegStudents.setText("Register");
        jMenuItemRegStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegStudentsActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemRegStudents);

        registrationMenu.add(jMenu4);

        jMenu5.setText("Teachers");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItemRegTeachers.setText("Register");
        jMenuItemRegTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegTeachersActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemRegTeachers);

        MenuItemActivate.setText("Acitvate ");
        MenuItemActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActivateActionPerformed(evt);
            }
        });
        jMenu5.add(MenuItemActivate);

        MenuItemDeactivate.setText("DeActivate");
        MenuItemDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDeactivateActionPerformed(evt);
            }
        });
        jMenu5.add(MenuItemDeactivate);

        registrationMenu.add(jMenu5);

        jMenu6.setText("Time Table");

        MenuItemCreate.setText("Create");
        MenuItemCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCreateActionPerformed(evt);
            }
        });
        jMenu6.add(MenuItemCreate);

        MenuItemGenerate.setText("Generate");
        jMenu6.add(MenuItemGenerate);

        registrationMenu.add(jMenu6);

        jMenuBar1.add(registrationMenu);

        jMenu3.setText("Options");

        createOptions.setText("Create Options");

        bloodGroup.setText("Blood Group");
        bloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupActionPerformed(evt);
            }
        });
        createOptions.add(bloodGroup);

        genotype.setText("Genotype");
        genotype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genotypeActionPerformed(evt);
            }
        });
        createOptions.add(genotype);

        religion.setText("Religion");
        religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religionActionPerformed(evt);
            }
        });
        createOptions.add(religion);

        sex.setText("Sex");
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });
        createOptions.add(sex);

        jMenuItem4.setText("Tribal Group");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        createOptions.add(jMenuItem4);

        jMenuItem10.setText("Language");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        createOptions.add(jMenuItem10);

        colour_of_the_eyes.setText("Colour of the eyes");
        colour_of_the_eyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colour_of_the_eyesActionPerformed(evt);
            }
        });
        createOptions.add(colour_of_the_eyes);

        state.setText("State");
        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        createOptions.add(state);

        local_govt.setText("Local Govt.");
        local_govt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                local_govtActionPerformed(evt);
            }
        });
        createOptions.add(local_govt);

        country.setText("Country");
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });
        createOptions.add(country);

        class_name.setText("Class");
        class_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_nameActionPerformed(evt);
            }
        });
        createOptions.add(class_name);

        subject.setText("Subject");
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });
        createOptions.add(subject);

        menuItemAcademicSession.setText("Academic Session");
        menuItemAcademicSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAcademicSessionActionPerformed(evt);
            }
        });
        createOptions.add(menuItemAcademicSession);

        menuItemMaritalStatus.setText("Marital Status");
        menuItemMaritalStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMaritalStatusActionPerformed(evt);
            }
        });
        createOptions.add(menuItemMaritalStatus);

        menuItemAcademicTerm.setText("Academic Term");
        menuItemAcademicTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAcademicTermActionPerformed(evt);
            }
        });
        createOptions.add(menuItemAcademicTerm);

        menuItemTimeTablePeriod.setText("Time Table Period");
        menuItemTimeTablePeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTimeTablePeriodActionPerformed(evt);
            }
        });
        createOptions.add(menuItemTimeTablePeriod);

        menuItemDayOfTheWeek.setText("Day of the week");
        menuItemDayOfTheWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDayOfTheWeekActionPerformed(evt);
            }
        });
        createOptions.add(menuItemDayOfTheWeek);

        jMenuItem11.setText("Level of Education");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        createOptions.add(jMenuItem11);

        jMenuItem12.setText("Discipline");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        createOptions.add(jMenuItem12);

        jMenuItem13.setText("Grade Obtained");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        createOptions.add(jMenuItem13);

        jMenuItemSchoolAttended.setText("School Attended");
        jMenuItemSchoolAttended.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSchoolAttendedActionPerformed(evt);
            }
        });
        createOptions.add(jMenuItemSchoolAttended);

        jMenuItemTeachersPosition.setText("Teachers Position");
        jMenuItemTeachersPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTeachersPositionActionPerformed(evt);
            }
        });
        createOptions.add(jMenuItemTeachersPosition);

        jMenuItemSpecialAilment.setText("Special Ailment");
        jMenuItemSpecialAilment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSpecialAilmentActionPerformed(evt);
            }
        });
        createOptions.add(jMenuItemSpecialAilment);

        jMenuItemFeeType.setText("Fee Type");
        jMenuItemFeeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFeeTypeActionPerformed(evt);
            }
        });
        createOptions.add(jMenuItemFeeType);

        jMenu3.add(createOptions);

        jMenu1.setText("Edit Options");
        jMenu3.add(jMenu1);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Mapping");

        menuItemSubjectToClass.setText("Subject To Class");
        menuItemSubjectToClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSubjectToClassActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemSubjectToClass);

        menuItemSubjectToTeacher.setText("Subject To Teacher");
        menuItemSubjectToTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSubjectToTeacherActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemSubjectToTeacher);

        menuItemTeacherToClass.setText("Teacher To Class");
        menuItemTeacherToClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTeacherToClassActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemTeacherToClass);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Student Affairs");

        jMenu9.setText("Attendance");

        jMenuItem8.setText("School Attendance");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem8);

        jMenuItem9.setText("Subject Attendance");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem9);

        jMenu7.add(jMenu9);

        jMenu10.setText("Continuous Assessment/ Exam");

        jMenuItem2.setText("New CA/Exam Setup ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem2);

        jMenuItem3.setText("Record Student Score");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem3);

        jMenu7.add(jMenu10);

        jMenuItem5.setText("Medicals");
        jMenu7.add(jMenuItem5);

        jMenuItem6.setText("ID Card");
        jMenu7.add(jMenuItem6);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Report");

        jMenuItem1.setText("Generate Time-Table");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        jMenuItem7.setText("Report Card");
        jMenu8.add(jMenuItem7);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "BG";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
    }//GEN-LAST:event_bloodGroupActionPerformed

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "ST";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
        
    }//GEN-LAST:event_stateActionPerformed

    private void genotypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genotypeActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "GT";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
    }//GEN-LAST:event_genotypeActionPerformed

    private void religionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_religionActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "RG";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
        
    }//GEN-LAST:event_religionActionPerformed

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "SX";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
        
    }//GEN-LAST:event_sexActionPerformed

    private void colour_of_the_eyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colour_of_the_eyesActionPerformed
        // TODO add your handling code here:
        GlobalVar.currentMenu = "COTE";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
        
    }//GEN-LAST:event_colour_of_the_eyesActionPerformed

    private void local_govtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_local_govtActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "LG";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
        
    }//GEN-LAST:event_local_govtActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "CT";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
        
    }//GEN-LAST:event_countryActionPerformed

    private void class_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_nameActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "CN";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
        
    }//GEN-LAST:event_class_nameActionPerformed

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "SJ";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
        
    }//GEN-LAST:event_subjectActionPerformed

    private void menuItemSubjectToClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSubjectToClassActionPerformed
        // TODO add your handling code here:
        
        SubjectToClass sub_class = new SubjectToClass(this, true);
        sub_class.setVisible(true);
        
        
    }//GEN-LAST:event_menuItemSubjectToClassActionPerformed

    private void menuItemSubjectToTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSubjectToTeacherActionPerformed
        // TODO add your handling code here:
        
        SubjectToTeacher sub_class_teacher = new SubjectToTeacher(this, true);
        sub_class_teacher.setVisible(true);
        
    }//GEN-LAST:event_menuItemSubjectToTeacherActionPerformed

    private void menuItemAcademicSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAcademicSessionActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "AS";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
        
    }//GEN-LAST:event_menuItemAcademicSessionActionPerformed

    private void menuItemMaritalStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMaritalStatusActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "MS";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
        
        
    }//GEN-LAST:event_menuItemMaritalStatusActionPerformed

    private void jMenuItemRegStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegStudentsActionPerformed
        // TODO add your handling code here:
        RegistrationDialog reg = new RegistrationDialog(this,true);
        reg.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegStudentsActionPerformed

    private void jMenuItemRegTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegTeachersActionPerformed
        // TODO add your handling code here:
        RegisterTeachers obj_Regteacher = new RegisterTeachers(this, true);
        obj_Regteacher.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegTeachersActionPerformed

    private void MenuItemActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActivateActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentActiveInactiveTeacher = "ACTIVATE";
        ActivateDeactivateTeacher actDeact = new ActivateDeactivateTeacher(this,true);
        actDeact.setVisible(true);
        
    }//GEN-LAST:event_MenuItemActivateActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
        
                
        GlobalVar.currentMenu = "ACTIVATE";
        ActivateDeactivateTeacher actDeact = new ActivateDeactivateTeacher(this,true);
        actDeact.setVisible(true);
        
        
        
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void MenuItemDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDeactivateActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentActiveInactiveTeacher = "DEACTIVATE";
        ActivateDeactivateTeacher actDeact = new ActivateDeactivateTeacher(this,true);
        actDeact.setVisible(true);
        
    }//GEN-LAST:event_MenuItemDeactivateActionPerformed

    private void menuItemTeacherToClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTeacherToClassActionPerformed
        // TODO add your handling code here:
          
        TeacherToClass sub_teacher_class = new TeacherToClass(this, true);
        sub_teacher_class.setVisible(true);
        
    }//GEN-LAST:event_menuItemTeacherToClassActionPerformed

    private void MenuItemCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCreateActionPerformed
        // TODO add your handling code here:
        
        TimeTablePeriod sub_timetable = new TimeTablePeriod(this, true);
        sub_timetable.setVisible(true);
        
    }//GEN-LAST:event_MenuItemCreateActionPerformed

    private void menuItemAcademicTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAcademicTermActionPerformed
        // TODO add your handling code here:
        GlobalVar.currentMenu = "ACATERM";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
         
        
        
    }//GEN-LAST:event_menuItemAcademicTermActionPerformed

    private void menuItemTimeTablePeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTimeTablePeriodActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "TTPERIOD";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
            
        
    }//GEN-LAST:event_menuItemTimeTablePeriodActionPerformed

    private void menuItemDayOfTheWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDayOfTheWeekActionPerformed
        // TODO add your handling code here:
        
        
        GlobalVar.currentMenu = "DOTW";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);
    }//GEN-LAST:event_menuItemDayOfTheWeekActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        
        
        SchoolAttendance obj = new SchoolAttendance(this, true);
        obj.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
                
        SubjectAttendance obj = new SubjectAttendance(this, true);
        obj.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        
        CA_Exam_Setup obj = new CA_Exam_Setup(this, true);
        obj.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
      
        CA_Exam obj = new CA_Exam(this, true);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        GlobalVar.currentMenu = "TRG";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
       
        GlobalVar.currentMenu = "LANG";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true);        

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed

        GlobalVar.currentMenu = "LOE";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true); 

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed

        GlobalVar.currentMenu = "DSP";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true); 


        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed

        GlobalVar.currentMenu = "GOBT";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true); 

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItemSchoolAttendedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSchoolAttendedActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "SCHATTD";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true); 
        
    }//GEN-LAST:event_jMenuItemSchoolAttendedActionPerformed

    private void jMenuItemTeachersPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTeachersPositionActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "TPOST";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true); 
        
        
    }//GEN-LAST:event_jMenuItemTeachersPositionActionPerformed

    private void jMenuItemSpecialAilmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSpecialAilmentActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "SPALM";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true); 
        
    }//GEN-LAST:event_jMenuItemSpecialAilmentActionPerformed

    private void jMenuItemFeeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFeeTypeActionPerformed
        // TODO add your handling code here:
        
        GlobalVar.currentMenu = "FEETYPE";
        OptionsDialog opt = new OptionsDialog(this,true);
        opt.setVisible(true); 
        
        
        
    }//GEN-LAST:event_jMenuItemFeeTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemActivate;
    private javax.swing.JMenuItem MenuItemCreate;
    private javax.swing.JMenuItem MenuItemDeactivate;
    private javax.swing.JMenuItem MenuItemGenerate;
    private javax.swing.JMenuItem bloodGroup;
    private javax.swing.JMenuItem class_name;
    private javax.swing.JMenuItem colour_of_the_eyes;
    private javax.swing.JMenuItem country;
    private javax.swing.JMenu createOptions;
    private javax.swing.JMenuItem genotype;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemFeeType;
    private javax.swing.JMenuItem jMenuItemRegStudents;
    private javax.swing.JMenuItem jMenuItemRegTeachers;
    private javax.swing.JMenuItem jMenuItemSchoolAttended;
    private javax.swing.JMenuItem jMenuItemSpecialAilment;
    private javax.swing.JMenuItem jMenuItemTeachersPosition;
    private javax.swing.JMenuItem local_govt;
    private javax.swing.JMenuItem menuItemAcademicSession;
    private javax.swing.JMenuItem menuItemAcademicTerm;
    private javax.swing.JMenuItem menuItemDayOfTheWeek;
    private javax.swing.JMenuItem menuItemMaritalStatus;
    private javax.swing.JMenuItem menuItemSubjectToClass;
    private javax.swing.JMenuItem menuItemSubjectToTeacher;
    private javax.swing.JMenuItem menuItemTeacherToClass;
    private javax.swing.JMenuItem menuItemTimeTablePeriod;
    private javax.swing.JMenu registrationMenu;
    private javax.swing.JMenuItem religion;
    private javax.swing.JMenuItem sex;
    private javax.swing.JMenuItem state;
    private javax.swing.JMenuItem subject;
    // End of variables declaration//GEN-END:variables
}
